spring.application.name=library-tracker

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5430/library_tracker}
spring.datasource.username=${DB_USERNAME:rizalamarulloh}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# JPA Auditing
spring.jpa.properties.hibernate.envers.audit_table_suffix=_aud

# Security JWT Configuration
application.security.jwt.secret-key=${JWT_TOKEN:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# OpenAPI Documentation
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Server Port
server.port=8080

# Logging
logging.level.org.springframework.security=DEBUG
